config/routes.rb
Bookbit::Application.routes.draw do
  resources :hexes

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  root "hexes#index" #root_path

  get "about" => "pages#about" #this line creates about_path

end

app/models/hex.rb
class Hex < ActiveRecord::Base
	belongs_to :user

	validates :hexcode, format: { with: /\A[a-fA-F0-9]{6}\z/, message: "not a valid hex code." }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :hexes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/hexes_controller.rb
class HexesController < ApplicationController
  before_action :set_hex, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  #Create = new and create
  #Read = show (ReadAll = index)
  #Update = edit and update
  #Destroy = destroy

  # GET /hexes
  # GET /hexes.json
  def index
    if user_signed_in?
      @hexes = current_user.hexes.order("created_at DESC")
    end
  end

  # GET /hexes/1
  # GET /hexes/1.json
  def show
  end

  # GET /hexes/new
  # Action for button of "Create Pin"
  def new
    @hex = current_user.hexes.build
  end

  # GET /hexes/1/edit
  def edit
  end

  # POST /hexes
  # POST /hexes.json
  def create
    @hex = current_user.hexes.build(hex_params)
    if @hex.save
      redirect_to hexes_url, notice: 'Hex was successfully added.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /hexes/1
  # PATCH/PUT /hexes/1.json
  def update
    if @hex.update(hex_params)
      redirect_to hexes_url, notice: 'Hex was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /hexes/1
  # DELETE /hexes/1.json
  def destroy
    @hex.destroy
    redirect_to hexes_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_hex
    @hex = Hex.find(params[:id])
  end

  def correct_user
    @hex = current_user.hexes.find_by(id: params[:id])
    redirect_to hexes_path if @hex.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def hex_params
    params.require(:hex).permit(:hexcode, :notes)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hexes_helper.rb
module HexesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hexes/_form.html.erb
<%= form_for @hex, html: {multipart: true} do |f| %>
  <% if @hex.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@hex.errors.count, "error") %> prohibited this hex from being saved:</h3>

      <ul>
      <% @hex.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :hexcode %><br>
    <%= f.text_field :hexcode, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_field :notes, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/hexes/edit.html.erb
<h1>Editing hex</h1>

<%= render 'form' %>

<%= link_to 'Show', @hex %> |
<%= link_to 'Back', hexes_path %>

app/views/hexes/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<% if user_signed_in? %>
<div class="box panel panel-default">
  <div class="panel-body">
    <%= link_to new_hex_path do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Hex
    <% end %>
  </div>
</div>

<div id="hexes" class="transitions-enabled">
  <% @hexes.each do |hex| %>
  <% if hex.user == current_user %>
  <div class="box panel panel-default">
    <div class="colorBox" style="background-color: #<%=hex.hexcode%>" onclick="copyToClipboard('#<%=hex.hexcode%>')" >
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-8">
          <strong>#<%= hex.hexcode.upcase %></strong>
        </div>
        <div class="col-xs-4 pull-right actions">
          <%= link_to edit_hex_path(hex) do %>
          <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= link_to hex, method: :delete, data: { confirm: ' Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </div>
      </div>
      <%= hex.notes %>
    </div>
  </div>
  <% end %>
  <% end %>
</div>


<% end %>

<script type="text/javascript">
  function copyToClipboard(text) {
    window.prompt("Copy to clipboard: Ctrl+C, Enter", text);
  }
</script>

app/views/hexes/new.html.erb
<h1>New hex</h1>

<%= render 'form' %>

<%= link_to 'Back', hexes_path %>

app/views/hexes/show.html.erb
<%= link_to 'Back', hexes_path %>

<div class="row">
	<div class="col-md-offset-5 col-md-2">
		<div class=" box panel panel-default">
			<div class="panel-heading colorBox" style="background-color: #<%=@hex.hexcode%>">
			</div>
			<div class="panel-body">
				<strong>#<%= @hex.hexcode.upcase %></strong>
				<% if @hex.user == current_user %>
					<%= link_to edit_hex_path(@hex) do %>
					<span class="glyphicon glyphicon-edit pull-right"></span>
					<% end %>
				<% end %>
				<br/>
				<%= @hex.notes %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "What's The Hex", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>What's The Hex</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>What's The Hex</h1>
	<p>
		<%= link_to "Sign in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
</div> <!-- jumbotron -->

app/views/pages/about.html.erb
<h1>About</h1>
<p>Keep track of colors you like or are using.</p>